kind = "web"
previewPath = "/"
title = "WirfonCloud"
version = "1.0.0"
id = "artifacts/wirfoncloud"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24427

[services.development]
run = "pnpm --filter @workspace/wirfoncloud run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/wirfoncloud", "run", "build" ]
publicDir = "artifacts/wirfoncloud/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24427"
BASE_PATH = "/"
